// The request body is provided in place
GET http://127.0.0.1:5000/group
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY4MzI5ODgyNiwianRpIjoiNzYxYzc1N2MtYTYyYi00ZTNmLTg4MWEtZTY3OTdjMWVkZDdmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Im1hdCIsIm5iZiI6MTY4MzI5ODgyNiwiZXhwIjoxNjgzMjk5NzI2fQ.7RTxuJ6EEGIyEhfyzTziLKvVoyjfsWPdLy4xKm1O9R4
Content-Type: application/json
Cookie: key=first-value


















