POST http://127.0.0.1:5000/rate HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY4NjU5NjAyMCwianRpIjoiNDkyZmVkMTEtNWNjYS00YjQyLTlkMjktNDkxZDJjY2I5YzNlIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjMxMzM4ODI0MSIsIm5iZiI6MTY4NjU5NjAyMCwiZXhwIjoxNjg2NTk2OTIwfQ.CL_m7U9AgXlc1YIuDJqxBPOviHXxAzk_J68QGLdY0sE
Content-Type: application/json
Cookie: key=first-value

{
  "data": {
    "group_number": 1,
    "rate": 5,
      "crowd_ratings": {
        "outstanding": 20,
        "very_good": 20,
        "good": 20,
        "fair": 20,
        "needs_improvement": 20
    },
    "answer": {"1": 1 , "2": 1}
  }
}


