// The request body is provided in place
GET http://127.0.0.1:5000/rate?group_number=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY4NjU5NTcwNiwianRpIjoiYTQzMzA0NTUtMDQ5OS00MWFiLTgwZWQtYjBkZDg5NmE1MTgxIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Im1hdCIsIm5iZiI6MTY4NjU5NTcwNiwiZXhwIjoxNjg2NTk2NjA2fQ.ujRxA4xAkBcOOoVW7QLng1cmzI1FGZHoBSNjwTc9sXw
Content-Type: application/json
Cookie: key=first-value



















