POST http://127.0.0.1:5000/rate HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY4NjUxNDI0MSwianRpIjoiMmU1NTljZTktYzU5NC00OTVjLTgyM2YtMzc0NTBmNDFlMWMyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Im1hdCIsIm5iZiI6MTY4NjUxNDI0MSwiZXhwIjoxNjg2NTE1MTQxfQ.dIyRhvj6ppINcHIP8WQ8iY6T5Y3RXqiFEo5XBh_CBaE
Content-Type: application/json
Cookie: key=first-value

{
  "data": {
    "group_number": 1,
    "rate": 5,
      "crowd_ratings": {
        "outstanding": 20,
        "very_good": 20,
        "good": 20,
        "fair": 20,
        "needs_improvement": 20
    },
    "text_answer": {"1": "some text" , "2": "some_other_text"}
  }
}


